#version 460
#extension GL_EXT_ray_tracing : require

layout(binding = 0, set = 0, rgba8) uniform writeonly image2D storageImage;

layout(location = 0) rayPayloadEXT vec3 hitValue;

void main() 
{
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy);
    const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);
    
    vec3 color = vec3(inUV, 0);

    imageStore(storageImage, ivec2(gl_LaunchIDEXT.xy), vec4(color, 1.0));
}
